name: Run Tests with Pytest on Multiple OS

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main  # Change if your default branch is different

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]


    env:
      OPIK_KEY: ${{ secrets.OPIK_KEY }}
      GPT4_ENDPOINT: ${{ secrets.GPT4_ENDPOINT }}
      AZURE_OPENAI_KEY_GPT_4: ${{ secrets.AZURE_OPENAI_KEY_GPT_4 }}
      AZURE_OPENAI_KEY_2: ${{ secrets.AZURE_OPENAI_KEY_2 }}
      AZURE_OPENAI_KEY: ${{ secrets.AZURE_OPENAI_KEY }}
      AZURE_OPENAI_ENDPOINT_2: ${{ secrets.AZURE_OPENAI_ENDPOINT_2 }}
      AZURE_OPENAI_ENDPOINT: ${{ secrets.AZURE_OPENAI_ENDPOINT }}

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      rabbitmq:
        image: rabbitmq:management
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd "rabbitmq-diagnostics -q ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      mongodb:
        image: mongo:latest
        ports:
          - 27017:27017
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.runCommand({ ping: 1 })' || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Set up Docker
        uses: docker/setup-docker-action@v4
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Verify API Key
        run: |
          if [ -z "$OPIK_KEY" ]; then
            echo "OPIK_KEY is not set!"
            exit 1
          else
            echo "OPIK_KEY is set."
          fi
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root
      - name: Run Test Cases
        run: poetry run pytest -s --maxfail=1 --disable-warnings -q




    
    